# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gian Lorenzetto
tagline:          'My blog and project spot'
description:      "My blog and projects spot, where I collect useful things relating to software development, mostly so I don't have to remember them."
url:              https://gianlorenzetto.githug.io
#url:              http://localhost:4000
baseurl:          /

author:
  name:           'Gian Lorenzetto'
  email:          gian.lorenzetto@gmail.com
  url:            https://twitter.com/TheZenDibbler

paginate:         5

# Social
social:
 - title: GitHub
   url: https://github.com/gianlorenzetto
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/gianlorenzetto
   class: linkedin
 - title: Twitter
   url: https://twitter.com/thezendibbler
   class: twitter

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gianlorenzetto/gianlorenzetto.github.io
