# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gian Lorenzetto
tagline:          'My blog and project spot'
description:      "My blog and projects spot, where I collect useful things relating to software development, mostly so I don't have to remember them."
url:              http://gianlorenzetto.githug.io
baseurl:          /

author:
  name:           'Gian Lorenzetto'
  email:          gian.lorenzetto@gmail.com
  url:            https://twitter.com/TheZenDibbler

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gianlorenzetto/gianlorenzetto.github.io
