# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zen Dibbler
tagline:          'My blog spot'
description:      "My IT and software blog, for writing things down so I don't have to remember."
url:              http://gianlorenzetto.githug.io
baseurl:          /

author:
  name:           'Gian Lorenzetto'
  email:          gian.lorenzetto@gmail.com
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gianlorenzetto/gianlorenzetto.github.io
