# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gian Lorenzetto
tagline:          "Gian's Blog"
description:      "All things relating to the art and science of software development."
url:              https://gianlorenzetto.github.io
#url:              http://localhost:4000
baseurl:          /

author:
  name:           'Gian Lorenzetto'
  email:          gian.lorenzetto@gmail.com
  url:            https://twitter.com/TheZenDibbler

paginate:         5

# Social
social:
 - title: GitHub
   url: https://github.com/gianlorenzetto
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/gianlorenzetto
   class: linkedin
 - title: Twitter
   url: https://twitter.com/thezendibbler
   class: twitter

# Excerpt separator
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gianlorenzetto/gianlorenzetto.github.io
