# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gian Lorenzetto
tagline:          "The art and science of software"
description:      "The art and science of software development."
url:              https://gianlorenzetto.github.io
baseurl:          /

author:
  name:           'Gian Lorenzetto'
  email:          gian.lorenzetto@gmail.com
  url:            https://twitter.com/TheZenDibbler

paginate:         5

# Social
social:
 - title: GitHub
   url: https://github.com/gianlorenzetto
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/gianlorenzetto
   class: linkedin
 - title: Google+
   url: https://plus.google.com/+GianLorenzetto
   class: googlep

# Comments
#  - Currently only supports Disqus
#  - To disable comments globally, set 'comments' to false.
#  - To disable comments for an individual port, set 'comments' to false in the
#    post front matter.
comments: true
disqus_shortname: giansblog

# Excerpt separator
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gianlorenzetto/gianlorenzetto.github.io
